name: vim-build

on:
  schedule:
    - cron: "45 5 * * Sun"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: clone https://github.com/Mental-Vortex/vim-builds
        uses: actions/checkout@master
        with:
          name: Mental-Vortex/vim-builds
          repository: Mental-Vortex/vim-builds
          path: ./vim-builds

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build vim-builds armv7 container
        uses: docker/build-push-action@v4
        with:
          context: ./vim-builds
          file: ./vim-builds/Dockerfile
          platforms: linux/arm/v7
          tags: Mental-Vortex/vim-builds-armv7:latest
          load: true
          
      -
        name: Build vim-builds armv6 container
        uses: docker/build-push-action@v4
        with:
          context: ./vim-builds
          file: ./vim-builds/Dockerfile
          platforms: linux/arm/v6
          tags: Mental-Vortex/vim-builds-armv6:latest
          load: true

      -
        name: Copy vim binaries from vim-builds container
        run: |
          # Copy vim binaries
          armv7_id=$(docker create --platform=linux/arm/v7 Mental-Vortex/vim-builds-armv7)
          armv6_id=$(docker create --platform=linux/arm/v6 Mental-Vortex/vim-builds-armv6)
          docker cp ${armv7_id}:/usr/local/bin/vim vim-armv7
          docker cp ${armv6_id}:/usr/local/bin/vim vim-armv6
          docker rm -f ${armv7_id}
          docker rm -f ${armv6_id}
          # Get version
          export VIM_VERSION=$(./vim-armv7 --version | head -1 | cut -d'(' -f1 | awk '{print $NF}')
          echo VIM_VERSION=${VIM_VERSION} >> $GITHUB_ENV
          # Remove vim-builds directory
          rm -rf vim-builds

      -
        name: Create release using compiled vim binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VIM_VERSION }}
          artifacts: 'vim-*'
          allowUpdates: true
          artifactErrorsFailBuild: false
